# Generated by Django 4.2.3 on 2023-09-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic', models.BooleanField(verbose_name='Automático')),
                ('charge_day', models.IntegerField(verbose_name='Dia de renovação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Assinatura')),
                ('base_price', models.FloatField(max_length=16, verbose_name='Preço base')),
                ('period', models.IntegerField(verbose_name='Período (em meses)')),
                ('description', models.CharField(max_length=512, verbose_name='Descrição')),
                ('subscription', models.ManyToManyField(through='subscription.Client_subscription', to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Data da transação')),
                ('end_date', models.DateField(verbose_name='Data de expiração')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='client_subscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
    ]
