# Generated by Django 4.2.1 on 2023-09-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_email_alter_user_cellphone_number_and_more'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.ManyToManyField(through='subscription.Client_subscription', to='authentication.client'),
        ),
    ]
