# Generated by Django 4.2.3 on 2023-08-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(verbose_name='Período (em meses)'),
        ),
    ]
