# Generated by Django 4.2.3 on 2023-08-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_date_joined_user_datetime_joined_and_more'),
        ('subscription', '0002_alter_subscription_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.ManyToManyField(through='subscription.Client_subscription', to='authentication.client'),
        ),
    ]
