# Generated by Django 4.2.1 on 2023-08-25 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='datetime_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.IntegerField(choices=[(1, 'Account created'), (2, 'Active account'), (3, 'Active'), (4, 'Disabled')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone_number',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='surname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('cellphone_number', models.CharField(max_length=11, unique=True)),
                ('datetime_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
        ),
    ]
