# Generated by Django 4.2.1 on 2023-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.IntegerField(choices=[(1, 'Account created'), (2, 'Active account'), (3, 'Active'), (4, 'Disabled')], default=1),
        ),
    ]
